export const users = [
    {
        email: 'mom@gabs.com',
        username: 'Gsbriel',
        firstName: 'Gabriel',
        lastName: 'Fajardo',
        planId: 1,
        creditBalance: 999,
    },
    {
        email: 'user1@example.com',
        username: 'user1',
        firstName: 'John',
        lastName: 'Doe',
        planId: 2,
        creditBalance: 500,
    },
    {
        email: 'user2@example.com',
        username: 'user2',
        firstName: 'Jane',
        lastName: 'Smith',
        planId: 3,
        creditBalance: 750,
    },
    {
        email: 'user3@example.com',
        username: 'user3',
        firstName: 'Michael',
        lastName: 'Johnson',
        planId: 1,
        creditBalance: 250,
    },
    {
        email: 'user4@example.com',
        username: 'user4',
        firstName: 'Emily',
        lastName: 'Brown',
        planId: 2,
        creditBalance: 1000,
    },
    {
        email: 'user5@example.com',
        username: 'user5',
        firstName: 'David',
        lastName: 'Miller',
        planId: 3,
        creditBalance: 800,
    },
    {
        email: 'user6@example.com',
        username: 'user6',
        firstName: 'Olivia',
        lastName: 'Davis',
        planId: 1,
        creditBalance: 600,
    },
    {
        email: 'user7@example.com',
        username: 'user7',
        firstName: 'James',
        lastName: 'Wilson',
        planId: 2,
        creditBalance: 400,
    },
    {
        email: 'user8@example.com',
        username: 'user8',
        firstName: 'Sophia',
        lastName: 'Taylor',
        planId: 3,
        creditBalance: 900,
    },
    {
        email: 'user9@example.com',
        username: 'user9',
        firstName: 'Daniel',
        lastName: 'Anderson',
        planId: 1,
        creditBalance: 700,
    },
    {
        email: 'user10@example.com',
        username: 'user10',
        firstName: 'Ava',
        lastName: 'Thomas',
        planId: 2,
        creditBalance: 1200,
    }
];


export const images = [
    {
        _id: 1,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'red',
        prompt: 'This is a red square',
    },
    {
        _id: 2,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'black',
        prompt: 'This is a black square',
    },
    {
        _id: 3,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'blue',
        prompt: 'This is a blue square',
    },
    {
        _id: 4,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'blue',
        prompt: 'This is a blue square',
    },
    {
        _id: 5,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'green',
        prompt: 'This is a green square',
    },
    {
        _id: 6,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'blue',
        prompt: 'This is a blue square',
    },
    {
        _id: 7,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'blue',
        prompt: 'This is a blue square',
    },
    {
        _id: 8,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'blue',
        prompt: 'This is a blue square',
    },
    {
        _id: 9,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'blue',
        prompt: 'This is a blue square',
    },
    {
        _id: 10,
        url: 'https://via.placeholder.com/150',
        width: 150,
        height: 150,
        color: 'grey',
        prompt: 'This is a grey square',
    }
];